# 参考: https://qiita.com/bellx2/items/4904c8a3aa13c6242d1c

FROM alpine


# puppeteer インストール & 設定

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser 

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    npm

RUN apk add --no-cache curl fontconfig \
    && curl -O https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip \
    && mkdir -p /usr/share/fonts/NotoSansCJKjp \
    && unzip NotoSansCJKjp-hinted.zip -d /usr/share/fonts/NotoSansCJKjp/ \
    && rm NotoSansCJKjp-hinted.zip \
    && fc-cache -fv


# typescript インストール & 設定

RUN npm install -g typescript discord.js @discordjs/rest discord-api-types puppeteer ts-node-dev
RUN mkdir -p /usr/srb4
RUN cd /usr/srb4
RUN tsc --init