version: '3'
services:

  bot:
    tty: true
    build:
      context: .
      dockerfile: dockerfile-bot
    image: bot
    
    container_name: bot

    volumes:
      - ../bot:/usr/srb3/source

    networks:
      - bot-api
    
    command: npx ts-node-dev --poll /usr/srb3/source/scripts/main.ts
  
  api:
    tty: true
    build:
      context: .
      dockerfile: dockerfile-api
    image: api

    container_name: api

    ports:
      - 8000:8000

    volumes:
      - ../api:/usr/srb3/source
    
    networks:
      - bot-api

volumes:
  srb3-db:

networks:
  bot-api: