FROM debian:buster-slim

# 必要パッケージインストール
RUN apt-get update \
    && apt-get -y install python3 python3-pip wget \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install fastapi uvicorn[standard] pymysql\
    && mkdir -p /usr/srb3/source

EXPOSE 8000