FROM debian:buster-slim

# 必要パッケージインストール
RUN apt-get update \
    && apt-get -y install python3 python3-pip wget \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install fastapi uvicorn[standard] pyppeteer \
    && mkdir -p /usr/srb3/source

EXPOSE 8000